In [1]:
from datetime import datetime
print(f'Päivitetty {datetime.now().date()} / Aki Taanila')

Päivitetty 2025-08-26 / Aki Taanila

# Lehtikauppiaan ongelma

Lehtikauppias on tilastoinut iltapäivälehden kysyntää. Kysyntä vaihtelee jonkin verran viikonpäivän 
mukaan. Lehtikauppias on laskenut tilaston perusteella kunkin viikonpäivän kysynnälle keskiarvon 
ja keskihajonnan. Tietyn viikonpäivän kysynnän voidaan olettaa noudattavan normaalijakaumaa.

Lehtikauppiaan täytyy ilmoittaa etukäteen tilattavien lehtien lukumäärä. Lehtikauppias pyrkii
tietenkin tyydyttämään kysynnän mahdollisimman hyvin ja toisaalta hankkimaan itselleen 
mahdollisimman korkean voiton. Simulointimallissa simuloidaan kysynnän määriä normaalijakaumasta ja lasketaan simulaatiokierrosten tilastolliset tunnusluvut voitolle ja puuttuvien lehtien määrälle.

Lehtikauppias voisi solmia nk. palautussopimuksen, jolloin myymättömistä lehdistä saa täyden 
hyvityksen lehtitalolta. Tässä tapauksessa lehden hinta on kauppiaalle korkeampi. Simulointimallissa on laskettu voiton tunnusluvut myös palautussopimusta käyttäen.

In [2]:
import numpy as np
import pandas as pd

In [3]:
TOISTOJA = 10000 #simulointikierrosten lukumäärä
KESKIARVO = 520 #päivämyynnin keskiarvo
KESKIHAJONTA = 50 #päivämyynnin keskihajonta
OSTOHINTA_EI_PALAUTUSTA = 0.25
OSTOHINTA_PALAUTUS = 0.33
MYYNTIHINTA = 1
yhteenveto = pd.DataFrame()

# Alustan satunnaislukugeneraattorin:
rng = np.random.default_rng()

for tilaus in range(510, 600, 10):
    kysyntä = rng.normal(loc = KESKIARVO, scale = KESKIHAJONTA, size = TOISTOJA)
    kysyntä = np.round(kysyntä)

    myynti = (kysyntä > tilaus) * tilaus + (kysyntä <= tilaus) * kysyntä

    voitto_palautus = myynti * (MYYNTIHINTA-OSTOHINTA_PALAUTUS)

    voitto_ei_palautusta = myynti * (MYYNTIHINTA - OSTOHINTA_EI_PALAUTUSTA) - (tilaus-myynti) * OSTOHINTA_PALAUTUS 
    
    ilman_lehteä = kysyntä - myynti

    yhteenveto['Palautus', tilaus] = voitto_palautus
    yhteenveto['Ei palautusta', tilaus] = voitto_ei_palautusta
    yhteenveto['Ilman lehteä', tilaus] = ilman_lehteä 

yhteenveto.mean() #voittojen ja ilman lehteä jääneiden keskiarvot eri tapauksissa

(Palautus, 510)         331.348433
(Ei palautusta, 510)    365.813892
(Ilman lehteä, 510)      25.882100
(Palautus, 520)         334.866469
(Ei palautusta, 520)    368.184756
(Ilman lehteä, 520)      19.023700
(Palautus, 530)         338.444001
(Ei palautusta, 530)    370.651524
(Ilman lehteä, 530)      15.274600
(Palautus, 540)         341.452100
(Ei palautusta, 540)    372.200400
(Ilman lehteä, 540)      12.062500
(Palautus, 550)         343.010587
(Ei palautusta, 550)    371.412588
(Ilman lehteä, 550)       8.725700
(Palautus, 560)         344.390988
(Ei palautusta, 560)    370.337712
(Ilman lehteä, 560)       6.315000
(Palautus, 570)         345.762277
(Ei palautusta, 570)    369.248148
(Ilman lehteä, 570)       4.274200
(Palautus, 580)         346.699674
(Ei palautusta, 580)    367.459176
(Ilman lehteä, 580)       2.655400
(Palautus, 590)         347.688393
(Ei palautusta, 590)    365.752932
(Ilman lehteä, 590)       1.905100
dtype: float64

In [4]:
yhteenveto.describe().style.format('{:.0f}') #tarkempi analyysi eri tapauksista

Lisätietoa satunnaislukujen tuottamisesta: https://numpy.org/doc/stable/reference/random/index.html